Repository YAPP-Github/pyeonlee-aos, pull requests merged in 2023-07, with the labels that each got.

#37 [FEATURE] #36 탐색 화면의 정렬 UI 구성
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/model/src/main/java/com/peonlee/model/type/SortType.kt
  core/model/src/main/res/values/strings.xml
  feature/evaluate/build.gradle.kts
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreViewModel.kt
  feature/explore/src/main/res/layout/fragment_explore.xml
  gradle/libs.versions.toml
Labels: 🌹진연주(AOS), 💻 Feature

#46 [FEATURE] #39 마이페이지 화면 UI 구성하기
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/SmallChip.kt
  core/ui/src/main/res/values/attrs.xml
  feature/login/src/main/res/values-night/themes.xml
  feature/main/build.gradle.kts
  feature/user/.gitignore
  feature/user/build.gradle.kts
  feature/user/src/main/AndroidManifest.xml
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  feature/user/src/main/res/layout/fragment_user.xml
  feature/user/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#48 [FEATURE] #42 메인 화면 API 연동하기
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/data/src/main/java/com/peonlee/data/Result.kt
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/peonlee/domain/login/GetHomeProductUseCase.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/peonlee/model/product/ProductUiModel.kt
  core/model/src/main/java/com/peonlee/model/type/PromotionType.kt
  core/model/src/main/java/com/peonlee/model/type/SortType.kt
  core/model/src/main/java/com/peonlee/model/type/StoreType.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreViewModel.kt
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/HomeViewModel.kt
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/divider/DividerViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/divider/HomeDividerViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ConditionalProductsViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/model/divider/HomeDividerUiModel.kt
  feature/home/src/main/java/com/peonlee/home/model/product/ConditionalProductsUiModel.kt
  feature/home/src/main/java/com/peonlee/home/model/product/EventByStoresUiModel.kt
  feature/home/src/main/res/layout/list_item_home_divider.xml
  gradle/libs.versions.toml
Labels: 🌹진연주(AOS), 💻 Feature

#50 [FEATURE] #15 평가, 온보딩 화면 구현
  core/data/build.gradle.kts
  core/data/src/main/java/com/peonlee/data/evaluate/EvaluatePagingSource.kt
  core/data/src/main/java/com/peonlee/data/evaluate/EvaluateRepository.kt
  core/data/src/main/java/com/peonlee/data/product/ProductApi.kt
  core/domain/src/main/java/com/peonlee/domain/evaluate/EvaluateProductUseCase.kt
  core/ui/src/main/java/com/peonlee/core/ui/util/spannable/TextSpannable.kt
  feature/evaluate/build.gradle.kts
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateAdapter.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewHolder.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewModel.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/OnboardActivity.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/SwipeCallback.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/SwipeCallbackListener.kt
  feature/evaluate/src/main/res/layout/fragment_evaluate.xml
  feature/evaluate/src/main/res/layout/layout_evaluate_snackbar.xml
  feature/evaluate/src/main/res/layout/list_item_evaluate.xml
  feature/evaluate/src/main/res/values/dimens.xml
  feature/evaluate/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐦 정지원(AOS)

#51 [FEATRUE] #49 검색 화면 구현
  app/build.gradle.kts
  feature/explore/build.gradle.kts
  feature/explore/src/main/AndroidManifest.xml
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/explore/src/main/res/layout/activity_explore_activity.xml
  feature/explore/src/main/res/values/dimens.xml
  feature/explore/src/main/res/values/strings.xml
Labels: 🐦 정지원(AOS)

#53 [UI] #52 스플래쉬, 로그인 화면 디자인 반영
  app/src/main/res/values/themes.xml
  core/ui/src/main/res/drawable/btn_google_login.xml
  core/ui/src/main/res/drawable/btn_kakao_login.xml
  core/ui/src/main/res/drawable/ic_logo_brand_symbol_splash_white.xml
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/res/layout/activity_login.xml
  feature/login/src/main/res/values/dimens.xml
Labels: 🐦 정지원(AOS)

#57 [FEATURE] #38 탐색 화면의 필터링 UI 구성
  core/common/src/main/java/com/peonlee/common/ext/IntExtension.kt
  core/data/src/main/java/com/peonlee/data/model/ProductSearch.kt
  core/data/src/main/java/com/peonlee/data/model/request/ProductSearchRequest.kt
  core/data/src/main/java/com/peonlee/data/product/DefaultProductRepository.kt
  core/data/src/main/java/com/peonlee/data/product/ProductApi.kt
  core/data/src/main/java/com/peonlee/data/product/ProductPagingSource.kt
  core/data/src/main/java/com/peonlee/data/product/ProductRepository.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/peonlee/model/product/ProductSearchConditionUiModel.kt
  core/model/src/main/java/com/peonlee/model/type/Category.kt
  core/model/src/main/java/com/peonlee/model/type/EventType.kt
  core/model/src/main/java/com/peonlee/model/type/PriceFilter.kt
  core/model/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/peonlee/core/ui/adapter/decoration/ContentPaddingDecoration.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseBottomSheetFragment.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/SmallChip.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/selector/SmallSelector.kt
  core/ui/src/main/java/com/peonlee/core/ui/viewholder/product/ProductViewHolder.kt
  core/ui/src/main/res/drawable/bg_product_image.xml
  core/ui/src/main/res/layout/base_bottomsheet_dialog.xml
  core/ui/src/main/res/layout/list_item_product.xml
  core/ui/src/main/res/values/themes.xml
  feature/detail/src/main/java/com/peonlee/feature/detail/ProductDetailListAdapter.kt
  feature/evaluate/build.gradle.kts
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewHolder.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/SwipeCallback.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreViewModel.kt
  feature/explore/src/main/res/layout/fragment_explore.xml
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/product/.gitignore
  feature/product/build.gradle.kts
  feature/product/src/main/AndroidManifest.xml
  feature/product/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/product/src/main/java/com/peonlee/product/ProductViewModel.kt
  feature/product/src/main/java/com/peonlee/product/adapter/FilterAdapter.kt
  feature/product/src/main/java/com/peonlee/product/adapter/ProductPagingAdapter.kt
  feature/product/src/main/java/com/peonlee/product/adapter/viewholder/FilterViewHolder.kt
  feature/product/src/main/java/com/peonlee/product/model/BaseFilter.kt
  feature/product/src/main/java/com/peonlee/product/ui/CategoryFilterBottomSheetFragment.kt
  feature/product/src/main/java/com/peonlee/product/ui/EventFilterBottomSheetFragment.kt
  feature/product/src/main/java/com/peonlee/product/ui/PriceFilterBottomSheetFragment.kt
  feature/product/src/main/res/drawable/divider_filter_sheet.xml
  feature/product/src/main/res/layout/fragment_product.xml
  feature/product/src/main/res/layout/item_filter_chip.xml
  feature/product/src/main/res/layout/item_filter_selector.xml
  feature/product/src/main/res/layout/item_price_filter.xml
  feature/product/src/main/res/layout/item_selector_filter.xml
  feature/product/src/main/res/layout/layout_price_filter.xml
  feature/product/src/main/res/layout/layout_selector_filter.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#59 [Hotfix] 홈 화면에서 상품 정보를 불러오지 못한 이슈 해결
  core/data/src/main/java/com/peonlee/data/product/DefaultProductRepository.kt
  feature/home/src/main/java/com/peonlee/home/HomeViewModel.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ProductsByStoreViewHolder.kt
  feature/home/src/main/res/layout/pager_item_products_by_store.xml
Labels: bug

#63 [FEATURE] #60 검색 화면 상품 목록 연동
  core/data/src/main/java/com/peonlee/data/product/ProductApi.kt
  core/data/src/main/java/com/peonlee/data/product/ProductRepository.kt
  core/domain/src/main/java/com/peonlee/domain/login/GetHomeProductUseCase.kt
  core/ui/src/main/java/com/peonlee/core/ui/extensions/EditTextExtension.kt
  core/ui/src/main/res/layout/list_item_product.xml
  feature/detail/src/main/java/com/peonlee/feature/detail/ProductCommentsActivity.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/explore/src/main/res/layout/activity_explore_activity.xml
  feature/product/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/product/src/main/java/com/peonlee/product/ProductViewModel.kt
Labels: 🐦 정지원(AOS), 💻 Feature

#65 [REFACTOR] 검색화면 로직 변경
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreViewModel.kt
  feature/explore/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/explore/src/main/java/com/peonlee/product/ProductViewModel.kt
Labels: 🐦 정지원(AOS)

#66 [REFACTOR] 평가 화면 로직 변경
  app/build.gradle.kts
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/OnboardActivity.kt
  feature/evaluate/src/main/res/layout/fragment_evaluate.xml
Labels: 🛠 Refactor, 🐦 정지원(AOS)

#71 [FEATURE] Access Token Interceptor 추가
  core/data/src/main/java/com/peonlee/data/di/NetworkModule.kt
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
Labels: 💻 Feature

#72 [FEATURE] #29 메인화면 Bottom Navigation을 이용한 Fragment 전환 구현
  app/build.gradle.kts
  core/data/src/main/java/com/peonlee/data/evaluate/EvaluatePagingSource.kt
  core/data/src/main/java/com/peonlee/data/product/ProductApi.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseFragment.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/Navigatable.kt
  feature/evaluate/build.gradle.kts
  feature/evaluate/src/main/AndroidManifest.xml
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewModel.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/java/com/peonlee/main/MainAdapter.kt
  feature/main/src/main/java/com/peonlee/main/MainViewModel.kt
  feature/main/src/main/res/anim/slide_in_left.xml
  feature/main/src/main/res/anim/slide_in_right.xml
  feature/main/src/main/res/anim/slide_out_left.xml
  feature/main/src/main/res/anim/slide_out_right.xml
  feature/main/src/main/res/color/bg_nav_icon.xml
  feature/main/src/main/res/layout/activity_main.xml
  feature/main/src/main/res/menu/home_nav_menu.xml
  feature/main/src/main/res/values/anim.xml
  feature/onboard/.gitignore
  feature/onboard/build.gradle.kts
  feature/onboard/src/main/AndroidManifest.xml
  feature/onboard/src/main/java/com/peonlee/board/OnboardActivity.kt
  feature/onboard/src/main/res/layout/activity_onboading.xml
  feature/product/src/main/res/layout/item_filter_selector.xml
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#74 [FEATURE] #55 로그인 인증 API 연동
  .gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/peonlee/ui/SplashActivity.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/peonlee/data/di/DataStoreModule.kt
  core/data/src/main/java/com/peonlee/data/di/NetworkModule.kt
  core/data/src/main/java/com/peonlee/data/di/RepositoryModule.kt
  core/data/src/main/java/com/peonlee/data/evaluate/EvaluatePagingSource.kt
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
  core/data/src/main/java/com/peonlee/data/local/LocalDataSource.kt
  core/data/src/main/java/com/peonlee/data/login/DefaultLoginRepository.kt
  core/data/src/main/java/com/peonlee/data/login/LoginApi.kt
  core/data/src/main/java/com/peonlee/data/login/LoginRepository.kt
  core/data/src/main/java/com/peonlee/data/login/LoginRepositoryImpl.kt
  core/data/src/main/java/com/peonlee/data/model/login/AuthFailResult.kt
  core/data/src/main/java/com/peonlee/data/model/login/AuthRequest.kt
  core/data/src/main/java/com/peonlee/data/model/login/AuthResult.kt
  core/data/src/main/java/com/peonlee/data/review/DefaultReviewRepository.kt
  core/data/src/main/java/com/peonlee/data/review/ReviewApi.kt
  core/data/src/main/java/com/peonlee/data/review/ReviewRepository.kt
  core/domain/src/main/java/com/peonlee/domain/login/LoginUseCase.kt
  feature/detail/src/main/java/com/peonlee/feature/detail/CommentHeaderViewHolder.kt
  feature/detail/src/main/java/com/peonlee/feature/detail/ProductCommentsPagingAdapter.kt
  feature/detail/src/main/java/com/peonlee/feature/detail/ProductDetailListAdapter.kt
  feature/detail/src/main/java/com/peonlee/feature/detail/ProductDetailViewModel.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewModel.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/java/com/peonlee/login/LoginViewModel.kt
  feature/login/src/main/res/values/string.xml
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  gradle/libs.versions.toml
Labels: 🐦 정지원(AOS), 💻 Feature

#79 [FEATURE] #75 약관동의 화면 구현
  app/src/main/java/com/peonlee/PeonleeApplication.kt
  core/ui/src/main/res/drawable/bg_brand30_outline_brand60_radius_10dp.xml
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/java/com/peonlee/login/LoginViewModel.kt
  feature/login/src/main/res/values/string.xml
  feature/terms/build.gradle.kts
  feature/terms/src/androidTest/java/com/peonlee/feature/terms/ExampleInstrumentedTest.kt
  feature/terms/src/main/AndroidManifest.xml
  feature/terms/src/main/java/com/peonlee/feature/terms/TermsActivity.kt
  feature/terms/src/main/res/layout/activity_terms.xml
  feature/terms/src/main/res/values/dimens.xml
  feature/terms/src/main/res/values/strings.xml
  feature/terms/src/test/java/com/peonlee/feature/terms/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🐦 정지원(AOS), 💻 Feature

#80 [REFACTOR] 평가 API 수정 및 어노테이션 추가
  core/data/src/main/java/com/peonlee/data/evaluate/EvaluatePagingSource.kt
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
  core/data/src/main/java/com/peonlee/data/model/login/AuthRequest.kt
  core/data/src/main/java/com/peonlee/data/product/ProductApi.kt
  feature/main/src/main/java/com/peonlee/main/MainAdapter.kt
Labels: 🛠 Refactor, 🐦 정지원(AOS)

#81 [FEATURE] 메인화면 Bottom Navigation을 이용한 Fragment 전환 구현 #29
  feature/evaluate/src/androidTest/java/com/peonlee/evaluate/ExampleInstrumentedTest.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewModel.kt
  feature/evaluate/src/main/res/layout/fragment_evaluate.xml
  feature/evaluate/src/test/java/com/peonlee/evaluate/ExampleUnitTest.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/java/com/peonlee/main/MainAdapter.kt
  feature/main/src/main/res/layout/activity_main.xml
  feature/onboading/.gitignore
  feature/onboading/build.gradle.kts
  feature/onboading/src/main/AndroidManifest.xml
  feature/onboading/src/main/java/com/peonlee/onboading/OnboardActivity.kt
  feature/onboading/src/main/java/com/peonlee/onboading/OnboardViewModel.kt
  feature/onboading/src/main/res/layout/activity_onboading.xml
  feature/onboading/src/main/res/values/strings.xml
  feature/product/src/main/res/layout/fragment_product.xml
  gradle/libs.versions.toml
Labels: 🌹진연주(AOS), 💻 Feature

#83 [FEAT] 탐색화면의 이동 로직 추가 #82
  app/src/main/java/com/peonlee/PeonLeeNavigator.kt
  core/ui/src/main/java/com/peonlee/core/ui/Navigator.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/res/layout/activity_explore_activity.xml
Labels: 🌹진연주(AOS), 💻 Feature

#88 [FEATURE] #87 마이페이지 API 연동
  core/data/src/main/java/com/peonlee/data/di/NetworkModule.kt
  core/data/src/main/java/com/peonlee/data/di/RepositoryModule.kt
  core/data/src/main/java/com/peonlee/data/model/user/UserResponse.kt
  core/data/src/main/java/com/peonlee/data/user/DefaultUserRepository.kt
  core/data/src/main/java/com/peonlee/data/user/UserApi.kt
  core/data/src/main/java/com/peonlee/data/user/UserRepository.kt
  feature/user/build.gradle.kts
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  feature/user/src/main/java/com/peonlee/user/UserViewModel.kt
  feature/user/src/main/java/com/peonlee/user/model/UserUiModel.kt
Labels: 🌹진연주(AOS), 💻 Feature

#89 [FEATURE] 메인화면 ViewPager 제거
  app/build.gradle.kts
  app/src/main/java/com/peonlee/PeonLeeNavigator.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/peonlee/model/product/ProductSearchConditionUiModel.kt
  core/model/src/main/java/com/peonlee/model/type/SortType.kt
  core/ui/src/main/java/com/peonlee/core/ui/Navigator.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseFragment.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/ProductSearchableViewModel.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreActivity.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/explore/ExploreViewModel.kt
  feature/explore/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/explore/src/main/java/com/peonlee/product/ProductViewModel.kt
  feature/explore/src/main/res/layout/activity_explore_activity.xml
  feature/explore/src/main/res/layout/fragment_explore.xml
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ConditionalProductsViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/EventByStoresViewHolder.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/java/com/peonlee/main/MainViewModel.kt
  feature/main/src/main/res/layout/activity_main.xml
Labels: 🌹진연주(AOS), 💻 Feature

#90 [REFACTOR] 로그인 로직 수정
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
  core/data/src/main/java/com/peonlee/data/model/Product.kt
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/java/com/peonlee/login/LoginViewModel.kt
Labels: 🐦 정지원(AOS), 💻 Feature

#93 [FEATURE] #86 설정화면 구현
  core/data/src/main/java/com/peonlee/data/user/DefaultUserRepository.kt
  core/data/src/main/java/com/peonlee/data/user/UserApi.kt
  core/data/src/main/java/com/peonlee/data/user/UserRepository.kt
  core/domain/src/main/java/com/peonlee/domain/user/UserUseCase.kt
  core/ui/src/main/res/layout/layout_user_review.xml
  feature/settings/build.gradle.kts
  feature/settings/src/androidTest/java/com/peonlee/ExampleInstrumentedTest.kt
  feature/settings/src/main/AndroidManifest.xml
  feature/settings/src/main/java/com/peonlee/SettingAdapter.kt
  feature/settings/src/main/java/com/peonlee/SettingFragment.kt
  feature/settings/src/main/java/com/peonlee/SettingUiModel.kt
  feature/settings/src/main/java/com/peonlee/SettingViewHolder.kt
  feature/settings/src/main/res/layout/fragment_setting.xml
  feature/settings/src/main/res/layout/item_terms.xml
  feature/settings/src/main/res/values/dimens.xml
  feature/settings/src/main/res/values/strings.xml
  feature/settings/src/test/java/com/peonlee/ExampleUnitTest.kt
  feature/termsdetail/build.gradle.kts
  feature/termsdetail/src/androidTest/java/com/peonlee/termsdetail/ExampleInstrumentedTest.kt
  feature/termsdetail/src/main/AndroidManifest.xml
  feature/termsdetail/src/main/java/com/peonlee/termsdetail/TermsDetailActivity.kt
  feature/termsdetail/src/main/res/layout/activity_terms_detail_activity.xml
  feature/termsdetail/src/test/java/com/peonlee/termsdetail/ExampleUnitTest.kt
  feature/withdrawal/build.gradle.kts
  feature/withdrawal/src/androidTest/java/com/peonlee/ExampleInstrumentedTest.kt
  feature/withdrawal/src/main/AndroidManifest.xml
  feature/withdrawal/src/main/java/com/peonlee/WithdrawalActivity.kt
  feature/withdrawal/src/main/java/com/peonlee/WithdrawalViewModel.kt
  feature/withdrawal/src/main/res/layout/activity_withdrawal.xml
  feature/withdrawal/src/main/res/values/dimens.xml
  feature/withdrawal/src/main/res/values/strings.xml
  feature/withdrawal/src/test/java/com/peonlee/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🐦 정지원(AOS), 💻 Feature

#94 [FEATURE] 약관동의 디테일화면, 회원탈퇴 구현
  app/src/main/java/com/peonlee/PeonLeeNavigator.kt
  app/src/main/java/com/peonlee/ui/SplashActivity.kt
  core/data/src/main/java/com/peonlee/data/model/user/DeleteRequest.kt
  core/data/src/main/java/com/peonlee/data/user/DefaultUserRepository.kt
  core/data/src/main/java/com/peonlee/data/user/UserApi.kt
  core/data/src/main/java/com/peonlee/data/user/UserRepository.kt
  core/domain/src/main/java/com/peonlee/domain/user/UserUseCase.kt
  core/ui/src/main/java/com/peonlee/core/ui/Navigator.kt
  core/ui/src/main/res/values/strings.xml
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateViewModel.kt
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/java/com/peonlee/login/LoginViewModel.kt
  feature/settings/build.gradle.kts
  feature/settings/src/main/AndroidManifest.xml
  feature/settings/src/main/java/com/peonlee/SettingActivity.kt
  feature/settings/src/main/java/com/peonlee/SettingFragment.kt
  feature/settings/src/main/res/layout/activity_setting.xml
  feature/terms/build.gradle.kts
  feature/terms/src/main/java/com/peonlee/feature/terms/TermsActivity.kt
  feature/terms/src/main/res/layout/activity_terms.xml
  feature/terms/src/main/res/values/strings.xml
  feature/termsdetail/src/main/java/com/peonlee/termsdetail/TermsDetailActivity.kt
  feature/termsdetail/src/main/res/layout/activity_terms_detail_activity.xml
  feature/user/build.gradle.kts
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  feature/user/src/main/java/com/peonlee/user/UserViewModel.kt
  feature/withdrawal/build.gradle.kts
  feature/withdrawal/src/main/java/com/peonlee/WithdrawalActivity.kt
  feature/withdrawal/src/main/java/com/peonlee/WithdrawalViewModel.kt
  feature/withdrawal/src/main/res/layout/activity_withdrawal.xml
  feature/withdrawal/src/main/res/values/strings.xml
Labels: 🛠 Refactor, 🐦 정지원(AOS), 💻 Feature

#97 [FEATURE] #96 닉네임 변경 화면 구성 및 API 연동
  app/build.gradle.kts
  app/src/main/java/com/peonlee/PeonLeeNavigator.kt
  core/data/src/main/java/com/peonlee/data/model/user/ModifyUserNickname.kt
  core/data/src/main/java/com/peonlee/data/user/UserApi.kt
  core/data/src/main/java/com/peonlee/data/user/UserRepository.kt
  core/ui/src/main/java/com/peonlee/core/ui/Navigator.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseFragment.kt
  feature/user/src/main/AndroidManifest.xml
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  feature/user/src/main/java/com/peonlee/user/UserViewModel.kt
  feature/user/src/main/java/com/peonlee/user/modify/ModifyUserNicknameActivity.kt
  feature/user/src/main/java/com/peonlee/user/modify/ModifyUserNicknameViewModel.kt
  feature/user/src/main/res/layout/activity_modify_user_nickname.xml
  feature/user/src/main/res/layout/fragment_user.xml
  feature/user/src/main/res/values/strings.xml
Labels: 🌹진연주(AOS), 💻 Feature

#99 [FEATURE] 홈 화면의 이동 로직 추가 #84
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseFragment.kt
  core/ui/src/main/res/drawable/bg_non_ripple_radius_10dp.xml
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/res/layout/fragment_evaluate.xml
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/java/com/peonlee/product/ProductFragment.kt
  feature/explore/src/main/res/layout/fragment_explore.xml
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ProductsByStoreViewHolder.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/layout/list_item_event_stores.xml
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/java/com/peonlee/main/MainAdapter.kt
  feature/main/src/main/res/layout/activity_main.xml
  feature/product/src/main/res/layout/fragment_product.xml
  feature/review/src/main/java/com/peonlee/review/edit/EditReviewActivity.kt
  feature/review/src/main/res/layout/activity_edit_review.xml
  feature/user/src/main/java/com/peonlee/user/UserFragment.kt
  feature/user/src/main/res/layout/activity_modify_user_nickname.xml
Labels: 🌹진연주(AOS), 💻 Feature

#100 [FIX] 온보딩 로직 버그 수정
  app/src/main/java/com/peonlee/PeonLeeNavigator.kt
  app/src/main/res/values/strings.xml
  core/ui/src/main/java/com/peonlee/core/ui/Navigator.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/peonlee/login/LoginActivity.kt
  feature/login/src/main/java/com/peonlee/login/LoginViewModel.kt
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/res/layout/activity_main.xml
  feature/onboard/build.gradle.kts
  feature/user/src/main/res/layout/fragment_user.xml
Labels: 🐦 정지원(AOS)

#101 [BASE] Firebase Crashlytics, Analytics 연동
  app/build.gradle.kts
  build.gradle.kts
  core/data/src/main/java/com/peonlee/data/interceptor/AuthInterceptor.kt
  gradle/libs.versions.toml
Labels: 🏠 Base, 🐦 정지원(AOS)
