Repository YAPP-Github/pyeonlee-aos, pull requests merged in 2023-06, with the labels that each got.

#11 [BASE] #8 - BaseListAdapter 추가
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/peonlee/core/ui/BaseListAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/CommonViewHolder.kt
  core/ui/src/main/java/com/peonlee/core/ui/MultiTypeListAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/SingleTypeListAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/extensions/ContextExtensions.kt
  gradle/libs.versions.toml
Labels: 💻 Feature, 🪴현명준(AOS)

#13 Feature/#12 hilt module
  .github/workflows/dev.yml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidRepositoryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/const/Key.kt
  build-logic/convention/src/main/kotlin/ext/ProjectExtensions.kt
  build-logic/convention/src/main/kotlin/ext/configureRepository.kt
  build-logic/convention/src/main/kotlin/ext/configureSnsLogin.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/peonlee/data/MyModelRepository.kt
  core/data/src/main/java/com/peonlee/data/di/DataModule.kt
  core/data/src/main/java/com/peonlee/data/di/NetworkModule.kt
  core/data/src/main/java/com/peonlee/data/login/LoginApi.kt
  core/data/src/main/java/com/peonlee/data/login/LoginModule.kt
  gradle/libs.versions.toml
Labels: 🏠 Base, 🐦 정지원(AOS)

#18 [FEATURE]#17 디자인 시스템 2차 개발
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseCustomView.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/button/LargeButton.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/button/MediumButton.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/MediumChip.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/SmallChip.kt
  core/ui/src/main/res/drawable/bg_white_outline_radius_10dp.xml
  core/ui/src/main/res/drawable/bg_white_radius_10dp.xml
  core/ui/src/main/res/drawable/bg_white_radius_20dp.xml
  core/ui/src/main/res/drawable/bg_white_radius_4dp.xml
  core/ui/src/main/res/layout/peonlee_large_button.xml
  core/ui/src/main/res/layout/peonlee_medium_button.xml
  core/ui/src/main/res/layout/peonlee_medium_chip.xml
  core/ui/src/main/res/layout/peonlee_small_chip.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/dimens.xml
Labels: 🐦 정지원(AOS), 💻 Feature

#20 [FEATURE] #9 - 메인-홈 Fragment 구성 및 기본 ViewType(Title, Divider) 추가
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/model/.gitignore
  core/model/build.gradle.kts
  core/model/src/main/java/com/peonlee/model/ListItem.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/peonlee/core/ui/adapter/MultiTypeListAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseFragment.kt
  core/ui/src/main/res/values/dimens.xml
  feature/home/.gitignore
  feature/home/build.gradle.kts
  feature/home/src/main/AndroidManifest.xml
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/divider/DividerViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/title/TitleViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/model/divider/DividerUiModel.kt
  feature/home/src/main/java/com/peonlee/home/model/title/TitleUiModel.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/layout/list_item_divider.xml
  feature/home/src/main/res/layout/list_item_title.xml
  feature/main/.gitignore
  feature/main/build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  feature/main/src/main/res/layout/activity_main.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#23 [REFACTOR]#22 - PDS CustomView Refactor
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseCustomView.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/button/LargeButton.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/button/MediumButton.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/MediumChip.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/SmallChip.kt
  core/ui/src/main/res/drawable/bg_white_radius_10dp.xml
  core/ui/src/main/res/layout/peonlee_medium_button.xml
  core/ui/src/main/res/layout/peonlee_medium_chip.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/colors.xml
Labels: 🛠 Refactor, 🐦 정지원(AOS)

#28 [FEATURE]#19 디자인 시스템 3차 개발
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/selector/MediumSelector.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/selector/SmallSelector.kt
  core/ui/src/main/res/drawable/bg_store_outline_cu_radius_17dp.xml
  core/ui/src/main/res/drawable/bg_store_outline_gs25_radius_17dp.xml
  core/ui/src/main/res/drawable/bg_store_outline_seveneleven_radius_17dp.xml
  core/ui/src/main/res/drawable/bg_white_outline_brand100_radius_17dp.xml
  core/ui/src/main/res/drawable/bg_white_outline_radius_17dp.xml
  core/ui/src/main/res/drawable/ic_checkbox_off.xml
  core/ui/src/main/res/drawable/ic_checkbox_on.xml
  core/ui/src/main/res/drawable/peonlee_custom_checkbox.xml
  core/ui/src/main/res/layout/peonlee_medium_selector.xml
  core/ui/src/main/res/layout/peonlee_small_selector.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/dimens.xml
Labels: 🐦 정지원(AOS), 💻 Feature

#24 [FEATURE] #21 리뷰 작성 화면 UI 구성하기
  core/ui/src/main/java/com/peonlee/core/ui/base/BaseActivity.kt
  core/ui/src/main/java/com/peonlee/core/ui/extensions/EditTextExtension.kt
  core/ui/src/main/java/com/peonlee/core/ui/util/keyboard/KeyboardUtil.kt
  core/ui/src/main/java/com/peonlee/core/ui/util/keyboard/KeyboardVisibilityEvent.kt
  core/ui/src/main/java/com/peonlee/core/ui/util/keyboard/unregister/SimpleUnregister.kt
  core/ui/src/main/java/com/peonlee/core/ui/util/keyboard/unregister/Unregister.kt
  core/ui/src/main/res/values/themes.xml
  feature/login/src/main/res/values-night/themes.xml
  feature/review/.gitignore
  feature/review/build.gradle.kts
  feature/review/src/main/AndroidManifest.xml
  feature/review/src/main/java/com/peonlee/review/edit/EditReviewActivity.kt
  feature/review/src/main/java/com/peonlee/review/edit/EditReviewViewModel.kt
  feature/review/src/main/res/layout/activity_edit_review.xml
  feature/review/src/main/res/values/dimens.xml
  feature/review/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#25 [FEATURE] #9 메인-홈 화면의 조건별 상품 리스트 UI 추가
  core/model/src/main/java/com/peonlee/model/ListItem.kt
  core/model/src/main/java/com/peonlee/model/product/ProductUiModel.kt
  core/model/src/main/java/com/peonlee/model/type/ConditionType.kt
  core/model/src/main/java/com/peonlee/model/util/PaddingValues.kt
  core/ui/src/main/java/com/peonlee/core/ui/adapter/decoration/ContentPaddingDecoration.kt
  core/ui/src/main/java/com/peonlee/core/ui/adapter/product/ProductAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/button/LargeButton.kt
  core/ui/src/main/java/com/peonlee/core/ui/extensions/IntExtension.kt
  core/ui/src/main/java/com/peonlee/core/ui/extensions/ViewHolderExtension.kt
  core/ui/src/main/java/com/peonlee/core/ui/viewholder/product/ProductViewHolder.kt
  core/ui/src/main/res/drawable/ic_test_product.png
  core/ui/src/main/res/layout/list_item_product.xml
  core/ui/src/main/res/layout/peonlee_large_button.xml
  core/ui/src/main/res/values/dimens.xml
  core/ui/src/main/res/values/strings.xml
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ConditionalProductsViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/model/divider/DividerUiModel.kt
  feature/home/src/main/java/com/peonlee/home/model/product/ConditionalProductsUiModel.kt
  feature/home/src/main/java/com/peonlee/home/model/title/TitleUiModel.kt
  feature/home/src/main/res/layout/list_item_conditional_products.xml
  feature/home/src/main/res/layout/list_item_divider.xml
  feature/home/src/main/res/layout/list_item_title.xml
  feature/home/src/main/res/values/dimens.xml
  feature/home/src/main/res/values/strings.xml
Labels: 🌹진연주(AOS), 💻 Feature

#30 [FEATURE] #9 메인-홈 화면의 최근 리뷰 리스트 UI 추가
  app/build.gradle.kts
  core/common/.gitignore
  core/common/build.gradle.kts
  core/common/src/main/AndroidManifest.xml
  core/common/src/main/java/com/peonlee/common/util/TimeUtil.kt
  core/common/src/main/res/values/strings.xml
  core/model/src/main/java/com/peonlee/model/ListItem.kt
  core/ui/src/main/java/com/peonlee/core/ui/designsystem/chip/MediumChip.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/peonlee/home/HomeFragment.kt
  feature/home/src/main/java/com/peonlee/home/adapter/HomeAdapter.kt
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/review/RecentReviewViewHolder.kt
  feature/home/src/main/java/com/peonlee/home/model/review/RecentReviewUiModel.kt
  feature/home/src/main/res/layout/list_item_recent_review.xml
  feature/home/src/main/res/values/dimens.xml
  feature/home/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature

#31 [FEATRUE] #15 온보딩, 평가화면 모듈 생성 및 UI 구현
  app/build.gradle.kts
  feature/evaluate/build.gradle.kts
  feature/evaluate/src/androidTest/java/com/peonlee/evaluate/ExampleInstrumentedTest.kt
  feature/evaluate/src/main/AndroidManifest.xml
  feature/evaluate/src/main/java/com/peonlee/evaluate/EvaluateFragment.kt
  feature/evaluate/src/main/java/com/peonlee/evaluate/OnboardActivity.kt
  feature/evaluate/src/main/res/layout/activity_onboading.xml
  feature/evaluate/src/main/res/layout/fragment_evaluate.xml
  feature/evaluate/src/main/res/layout/list_item_evaluate.xml
  feature/evaluate/src/main/res/values/dimens.xml
  feature/evaluate/src/main/res/values/strings.xml
  feature/evaluate/src/test/java/com/peonlee/evaluate/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🐦 정지원(AOS), 💻 Feature

#35 [FEATURE] #34 탐색 화면의 상품 리스트 UI 구성
  core/ui/src/main/java/com/peonlee/core/ui/adapter/product/ProductAdapter.kt
  core/ui/src/main/java/com/peonlee/core/ui/viewholder/product/ProductViewHolder.kt
  core/ui/src/main/res/layout/list_item_product.xml
  feature/explore/.gitignore
  feature/explore/build.gradle.kts
  feature/explore/src/main/AndroidManifest.xml
  feature/explore/src/main/java/com/peonlee/explore/ExploreFragment.kt
  feature/explore/src/main/res/layout/fragment_explore.xml
  feature/home/src/main/java/com/peonlee/home/adapter/viewholder/product/ConditionalProductsViewHolder.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/peonlee/main/MainActivity.kt
  settings.gradle.kts
Labels: 🌹진연주(AOS), 💻 Feature
